openapi: 3.0.0
info:
  title: CWS-Lib-Go ECS API
  version: 1.0.0
paths:
  /instances:
    post:
      summary: CreateInstance
      parameters:
        - name: RegionId
          in: query
          required: true
          schema: 
            type: string
        - name: ImageId
          in: query
          required: true
          schema: 
            type: string
        - name: InstanceType
          in: query
          required: true
          schema: 
            type: string
        - name: SecurityGroupId
          in: query
          required: true
          schema: 
            type: string
        - name: VSwitchId
          in: query
          required: true
          schema: 
            type: string
