openapi: 3.0.0
info:
  title: OtsInstance Internal Contract
  version: 1.0.0
paths:
  /instances/vcu/create:
    post:
      summary: Create VCU Instance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                elastic_vcu_upper_limit:
                  type: number
                tags:
                  type: object
      description: |
        Internal mapping:
        InstanceSpecification = "VCU"
        ElasticVCUUpperLimit = input.elastic_vcu_upper_limit

  /instances/standard/create:
    post:
      summary: Create Standard Instance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instance_specification:
                  type: string
                  enum: ["SSD", "HYBRID"]
                tags:
                  type: object
      description: |
        Internal mapping:
        InstanceSpecification = input.instance_specification (Must NOT be "VCU")
        ElasticVCUUpperLimit = null
