# Project Instructions for AI Agents

## Project Overview
Terraform Provider for Alibaba Cloud (terraform-provider-alicloud) enables Terraform to manage Alibaba Cloud resources. It serves as a plugin that interfaces with Alibaba Cloud APIs to provision, update, and destroy infrastructure.

> **Note**: This file is generated by `/speckit.instructions`. Custom content is preserved during updates.

## Documentation Map
This project documentation is distributed across several key files. You MUST refer to these documents for specific details:

| Document | Location | Purpose | Key Content |
|----------|----------|---------|-------------|
| **Constitution** | `.specify/memory/constitution.md` | Single source of truth for principles | Architecture (Resource->Service->API), Strong Typing, State Management |
| **Feature Index** | `.specify/memory/features.md` | Feature roadmap status | List of project features |
| **Development** | `docs/development_guide.md` | Engineering Guidelines | Detailed coding standards, error handling, layer definitions |
| **Readme** | `README.md` | Basic Information | Project structure, requirements, supported versions |
| **Website Docs** | `website/docs/` | User Documentation | Terraform resource and data source documentation |

> **Directive**: When answering questions or generating code, ALWAYS check the relevant document from the map above first.

## Tech Stack & Resources
- **Project Name**: terraform-provider-alicloud
- **Root Path**: /cws_data/terraform-provider-alicloud

### Detected Tech Stack
- **Languages**: Go 1.20+
- **Frameworks**: Terraform Plugin SDK (HashiCorp)
- **Key Libraries**: 
  - `cws-lib-go` (Internal API wrapper)
  - `aliyun-openapi-go-sdk` (Underlying SDK)
- **Build Tools**: `make`, `go build`
- **Key Directories**:
  - `alicloud/`: Main provider code (Resources, Data Sources, Services)
  - `website/`: Documentation
  - `examples/`: Example configurations
  - `sdk/`: Local copies of specific Alibaba Cloud service SDKs
  - `bin/`: Compiled binaries

# Tool And Skills Usage Guide

> **Note**: Tool and Skills details are injected into prompts by the agent when needed. This section is guidance only.

## Suggested Tooling Scope (High-Level)
- System/Linux CLI and shell context (env vars, functions, aliases)
- Project scripts (Shell/Python) in `.specify/scripts/`
- MCP tools and skills (auto-injected)

## Guidance
- **Architectural Compliance**: Strictly follow the Layered Architecture defined in the Constitution.
- **Strong Typing**: Use `cws-lib-go` types; avoid `map[string]interface{}`.
- **State Management**: Use `WaitFor` logic in Service layer; do not poll in Resource Create.

## Tools
Project specific tools documentation can be found in `.ai/tools/`.
- [MCP Tools](.ai/tools/mcp.md)
- [System Tools](.ai/tools/system.md)
- [Shell Tools](.ai/tools/shell.md)
- [Project Scripts](.ai/tools/project.md)

## Skills
Project specific skills documentation can be found in `.github/skills/`.
