openapi: 3.0.0
info:
  title: Alibaba Cloud Kafka Topic API
  version: 1.0.0
  description: API for managing Alibaba Cloud Kafka topics

paths:
  /kafka/instances/{instanceId}/topics:
    get:
      summary: List Kafka topics
      operationId: listKafkaTopics
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  topics:
                    type: array
                    items:
                      $ref: '#/components/schemas/KafkaTopic'
    post:
      summary: Create a Kafka topic
      operationId: createKafkaTopic
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKafkaTopicRequest'
      responses:
        '201':
          description: Topic created successfully
        '400':
          description: Bad request
        '409':
          description: Topic already exists

  /kafka/instances/{instanceId}/topics/{topic}:
    get:
      summary: Get a Kafka topic
      operationId: getKafkaTopic
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: topic
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KafkaTopic'
        '404':
          description: Topic not found
    delete:
      summary: Delete a Kafka topic
      operationId: deleteKafkaTopic
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: topic
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Topic deleted successfully
        '404':
          description: Topic not found

components:
  schemas:
    KafkaTopic:
      type: object
      properties:
        topic:
          type: string
          description: Topic name
        instanceId:
          type: string
          description: ID of the instance to which the topic belongs
        partitionNum:
          type: integer
          description: Number of partitions
        remark:
          type: string
          description: Remark
        createTime:
          type: integer
          description: Creation timestamp
        status:
          type: integer
          description: Status
        compactTopic:
          type: boolean
          description: Indicates whether it is a Compact topic
        localTopic:
          type: boolean
          description: Indicates whether it is a local topic
        replicaNum:
          type: integer
          description: Number of replicas

    CreateKafkaTopicRequest:
      type: object
      properties:
        topic:
          type: string
          description: Topic name
        partitionNum:
          type: integer
          description: Number of partitions
        remark:
          type: string
          description: Remark
        replicaNum:
          type: integer
          description: Number of replicas