openapi: 3.0.0
info:
  title: Alibaba Cloud Kafka Consumer Group API
  version: 1.0.0
  description: API for managing Alibaba Cloud Kafka consumer groups

paths:
  /kafka/instances/{instanceId}/consumer-groups:
    get:
      summary: List Kafka consumer groups
      operationId: listKafkaConsumerGroups
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  consumerGroups:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConsumerGroup'
    post:
      summary: Create a Kafka consumer group
      operationId: createKafkaConsumerGroup
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKafkaConsumerGroupRequest'
      responses:
        '201':
          description: Consumer group created successfully
        '400':
          description: Bad request
        '409':
          description: Consumer group already exists

  /kafka/instances/{instanceId}/consumer-groups/{consumerGroupId}:
    get:
      summary: Get a Kafka consumer group
      operationId: getKafkaConsumerGroup
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: consumerGroupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumerGroup'
        '404':
          description: Consumer group not found
    delete:
      summary: Delete a Kafka consumer group
      operationId: deleteKafkaConsumerGroup
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: consumerGroupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Consumer group deleted successfully
        '404':
          description: Consumer group not found

components:
  schemas:
    ConsumerGroup:
      type: object
      properties:
        consumerGroupId:
          type: string
          description: Consumer group ID
        instanceId:
          type: string
          description: ID of the instance to which the consumer group belongs
        consumerGroupName:
          type: string
          description: Consumer group name
        consumerGroupType:
          type: string
          description: Consumer group type
        consumerGroupStatus:
          type: string
          description: Consumer group status
        consumerGroupDescription:
          type: string
          description: Consumer group description
        consumerGroupTags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Consumer group tags
        consumerGroupCreateTime:
          type: string
          description: Creation time
        consumerGroupUpdateTime:
          type: string
          description: Update time

    CreateKafkaConsumerGroupRequest:
      type: object
      properties:
        consumerGroupId:
          type: string
          description: Consumer group ID
        consumerGroupName:
          type: string
          description: Consumer group name
        consumerGroupDescription:
          type: string
          description: Consumer group description
        consumerGroupTags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Consumer group tags

    Tag:
      type: object
      properties:
        key:
          type: string
          description: Tag key
        value:
          type: string
          description: Tag value