openapi: 3.0.0
info:
  title: Alibaba Cloud Kafka SASL ACL API
  version: 1.0.0
  description: API for managing Alibaba Cloud Kafka SASL ACLs

paths:
  /kafka/instances/{instanceId}/sasl-acls:
    get:
      summary: List Kafka SASL ACLs
      operationId: listKafkaSaslAcls
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: username
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  saslAcls:
                    type: array
                    items:
                      $ref: '#/components/schemas/AclRule'
    post:
      summary: Create a Kafka SASL ACL
      operationId: createKafkaSaslAcl
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKafkaSaslAclRequest'
      responses:
        '201':
          description: SASL ACL created successfully
        '400':
          description: Bad request
        '409':
          description: SASL ACL already exists

  /kafka/instances/{instanceId}/sasl-acls/{aclId}:
    delete:
      summary: Delete a Kafka SASL ACL
      operationId: deleteKafkaSaslAcl
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: aclId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: SASL ACL deleted successfully
        '404':
          description: SASL ACL not found

components:
  schemas:
    AclRule:
      type: object
      properties:
        aclResourceType:
          type: string
          description: ACL resource type
        aclResourceName:
          type: string
          description: ACL resource name
        aclResourcePatternType:
          type: string
          description: ACL resource pattern type
        aclOperation:
          type: string
          description: ACL operation type
        aclPermissionType:
          type: string
          description: ACL permission type
        aclHost:
          type: string
          description: ACL host
        aclPrincipal:
          type: string
          description: ACL principal
        instanceId:
          type: string
          description: ID of the instance to which the ACL rule belongs

    CreateKafkaSaslAclRequest:
      type: object
      properties:
        username:
          type: string
          description: SASL username
        aclResourceType:
          type: string
          description: ACL resource type
        aclResourceName:
          type: string
          description: ACL resource name
        aclResourcePatternType:
          type: string
          description: ACL resource pattern type
        aclOperation:
          type: string
          description: ACL operation type
        aclPermissionType:
          type: string
          description: ACL permission type
        aclHost:
          type: string
          description: ACL host
        aclPrincipal:
          type: string
          description: ACL principal