openapi: 3.0.0
info:
  title: Alibaba Cloud Kafka SASL User API
  version: 1.0.0
  description: API for managing Alibaba Cloud Kafka SASL users

paths:
  /kafka/instances/{instanceId}/sasl-users:
    get:
      summary: List Kafka SASL users
      operationId: listKafkaSaslUsers
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  saslUsers:
                    type: array
                    items:
                      $ref: '#/components/schemas/SaslUser'
    post:
      summary: Create a Kafka SASL user
      operationId: createKafkaSaslUser
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKafkaSaslUserRequest'
      responses:
        '201':
          description: SASL user created successfully
        '400':
          description: Bad request
        '409':
          description: SASL user already exists

  /kafka/instances/{instanceId}/sasl-users/{username}:
    get:
      summary: Get a Kafka SASL user
      operationId: getKafkaSaslUser
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaslUser'
        '404':
          description: SASL user not found
    delete:
      summary: Delete a Kafka SASL user
      operationId: deleteKafkaSaslUser
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: SASL user deleted successfully
        '404':
          description: SASL user not found

components:
  schemas:
    SaslUser:
      type: object
      properties:
        instanceId:
          type: string
          description: ID of the instance to which the user belongs
        username:
          type: string
          description: Username
        mechanism:
          type: string
          description: Authentication mechanism

    CreateKafkaSaslUserRequest:
      type: object
      properties:
        username:
          type: string
          description: Username
        password:
          type: string
          description: Password
        mechanism:
          type: string
          description: Authentication mechanism