openapi: 3.0.0
info:
  title: Alibaba Cloud Kafka Allowed IP API
  version: 1.0.0
  description: API for managing Alibaba Cloud Kafka allowed IP configurations

paths:
  /kafka/instances/{instanceId}/allowed-ips:
    get:
      summary: List Kafka allowed IP configurations
      operationId: listKafkaAllowedIps
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowedIps:
                    type: array
                    items:
                      $ref: '#/components/schemas/AllowedIp'
    post:
      summary: Create a Kafka allowed IP configuration
      operationId: createKafkaAllowedIp
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKafkaAllowedIpRequest'
      responses:
        '201':
          description: Allowed IP configuration created successfully
        '400':
          description: Bad request
        '409':
          description: Allowed IP configuration already exists

  /kafka/instances/{instanceId}/allowed-ips/{allowedIpId}:
    delete:
      summary: Delete a Kafka allowed IP configuration
      operationId: deleteKafkaAllowedIp
      parameters:
        - name: instanceId
          in: path
          required: true
          schema:
            type: string
        - name: allowedIpId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Allowed IP configuration deleted successfully
        '404':
          description: Allowed IP configuration not found

components:
  schemas:
    AllowedIp:
      type: object
      properties:
        instanceId:
          type: string
          description: ID of the instance
        allowedType:
          type: string
          description: Allowed type (e.g., "vpc", "internet")
        portRange:
          type: string
          description: Port range
        allowedIpList:
          type: array
          items:
            type: string
          description: List of allowed IP addresses/CIDR blocks

    CreateKafkaAllowedIpRequest:
      type: object
      properties:
        allowedType:
          type: string
          description: Allowed type (e.g., "vpc", "internet")
        portRange:
          type: string
          description: Port range
        allowedIpList:
          type: array
          items:
            type: string
          description: List of allowed IP addresses/CIDR blocks