# Project Instructions for AI Agents

## Project Overview
Terraform Provider for Alibaba Cloud (terraform-provider-alicloud) enables Terraform to manage Alibaba Cloud resources. It is a Go-based Terraform plugin using `hashicorp/terraform-plugin-sdk` v1 that interfaces with Alibaba Cloud APIs to provision, update, and destroy infrastructure. The provider manages 1000+ resources and 700+ data sources across dozens of Alibaba Cloud services (ECS, OSS, SLS, AliKafka, ACK, ALB, etc.).

The codebase enforces a strict layered architecture: **Resource → Service → API (cws-lib-go) → SDK**. The `pkg/cws-lib-go` submodule provides strongly-typed API wrappers; direct SDK calls in the Resource layer are forbidden in new code.

> **Note**: This file is generated by `/speckit.instructions`. Custom content is preserved during updates.

## Documentation Map
This project documentation is distributed across several key files. You MUST refer to these documents for specific details:

| Document | Location | Purpose | Key Content |
|----------|----------|---------|-------------|
| **Constitution** | `.specify/memory/constitution.md` | Single source of truth for principles | Coding standards, architectural rules, constraints |
| **Feature Index** | `.specify/memory/features.md` | Feature roadmap status | 11 tracked features with spec/plan links |
| **Development Guide** | `docs/development_guide.md` | Engineering constraints | Specific engineering rules (authoritative alongside Constitution) |
| **WaitFor Guide** | `docs/wait_for_state.md` | State management patterns | StateRefreshFunc and WaitFor* implementation guidance |
| **Readme** | `README.md` | Project overview | Supported Terraform versions, project structure, feature list |
| **cws-lib-go** | `pkg/cws-lib-go/` | API wrapper library | Strongly-typed Alibaba Cloud API wrappers and SDK integration |

> **Directive**: When answering questions or generating code, ALWAYS check the relevant document from the map above first.

## Fact, Correctness & Logic Checks (Input Sanity)
User-provided context can be wrong (misconceptions), incomplete, or contain typos. Before acting on user input, perform a basic sanity check to avoid propagating errors.

Minimum checks:
- **Names & identifiers**: Verify file paths, module/package names, commands, and symbols exist in the repo. If uncertain, search the workspace rather than guessing.
- **Factual claims**: Treat user statements as hypotheses; confirm against the repo (code/config), the Documentation Map, or authoritative references.
- **Logical consistency**: Detect contradictions between requirements, constraints, and desired outcomes (e.g., incompatible versions, mutually exclusive goals).
- **Typos & near-misses**: Correct obvious typos (paths, flags, option names) and explicitly state the corrected interpretation.
- **Assumptions**: If you must assume, keep assumptions minimal, label them clearly, and prefer reversible changes.

Escalation rules:
- If the suspected error impacts correctness, security, data loss, or large refactors: **pause and ask a clarifying question**.
- If the issue is low-risk and the fix is obvious: proceed with the correction and mention it briefly.

## Tech Stack & Resources
- **Project Name**: terraform-provider-alicloud
- **Root Path**: /cws_data/terraform-provider-alicloud
- **Language**: Go 1.24
- **Framework**: HashiCorp Terraform Plugin SDK v1 (`hashicorp/terraform-plugin-sdk v1.17.2`)
- **Key Dependencies**: `alibaba-cloud-sdk-go`, `cws-lib-go` (local submodule), `aliyungo`, various `alibabacloud-go/*` SDKs
- **Build Tool**: GNU Make (see `Makefile`)
- **Key Directories**:
  - `alicloud/`: Main provider code — resources (`resource_alicloud_*.go`), data sources (`data_source_alicloud_*.go`), service layers (`service_alicloud_*.go`), and connectivity
  - `alicloud/connectivity/`: Provider client configuration, endpoint management, and region definitions
  - `pkg/cws-lib-go/`: Git submodule — strongly-typed API wrappers for Alibaba Cloud services (the "API layer" in the architecture)
  - `docs/`: Development guide and engineering documentation
  - `examples/`: Example Terraform configurations
  - `bin/`: Build output directory (generated, not committed)

## Build & Test Commands
| Command | Purpose |
|---------|---------|
| `make` | Auto-detect OS and build (default target) |
| `make build` | Format check + build all platforms |
| `make linux` | Build Linux amd64 binary only |
| `make mac` / `make macarm` | Build macOS amd64 / ARM64 |
| `make dev` / `make devlinux` | Build + install to local Terraform plugin path |
| `make test` | Run unit tests (30s timeout, 4 parallel) |
| `make testacc` | Run acceptance tests (requires `TF_ACC=1`, 120m timeout) |
| `make fmt` | Format Go code (`gofmt` + `goimports`) |
| `make fmtcheck` | Check code formatting without modifying |
| `make vet` | Run `go vet` static analysis |

## Architecture Patterns
- **File naming**: `resource_alicloud_{service}_{resource}.go`, `data_source_alicloud_{service}_{resource}.go`, `service_alicloud_{service}.go`
- **Layered architecture**: Resource/DataSource → Service (`service_alicloud_*.go`) → API (`pkg/cws-lib-go`) → SDK. New code MUST NOT call SDKs directly from the Resource layer.
- **Strong typing**: `map[string]interface{}` is forbidden in new request/response types — use `cws-lib-go` typed structs.
- **State management**: Service layer implements `StateRefreshFunc` and `WaitFor*` methods. Resource `Create` methods must NOT contain polling loops.
- **Pagination**: Must be encapsulated in API/Service layer, never exposed to callers.
- **v2 convention**: Some services have `_v2.go` variants (e.g., `service_alicloud_ack_v2.go`) indicating newer API implementations.

# Tool And Skills Usage Guide
> **Note**: Tool and Skills details are injected into prompts by the agent when needed. This section is guidance only.

## Suggested Tooling Scope (High-Level)
- Prefer scripts under `.specify/scripts/` and `scripts/` for repeatable operations.
- `/speckit.*` commands are chat instructions, not terminal commands.
- Treat Constitution as the authority for architecture and workflow constraints.

## AI Tool Compatibility
- **Supported Agents**: Claude Code, GitHub Copilot, Qwen Code, opencode, Qoder
- **Instructions Refresh**: Run `/speckit.instructions` to regenerate this file and compatibility symlinks.

## Spec Kit Runtime & Symlink Model
- **Canonical instructions file**: `.specify/instructions.md` is the single source of truth for project-level AI instructions. Compatibility files such as `.github/copilot-instructions.md`, `.clinerules/project_rules.md`, `.lingma/rules/project_rule.md`, `.trae/rules/project_rules.md`, `.qoder/project_rules.md`, `.cursorrules`, `QWEN.md`, `CLAUDE.md`, `IFLOW.md`, and `QODER.md` are symlinks to this file.
- **Canonical skills directory**: `.specify/skills/` is the primary location for installed Spec Kit skills. `.github/skills` is a compatibility symlink to `.specify/skills/` for tools that discover skills under `.github/skills`.
- **Do not duplicate symlink targets**: Treat these compatibility paths as aliases, not independent source files or directories. When reading or editing instructions and skills, prefer the canonical `.specify/...` paths and avoid applying the same change separately through each symlink.
- **Regeneration behavior**: `/speckit.instructions` refreshes the instructions content and recreates compatibility symlinks. If a compatibility path appears to contain the same content as `.specify/instructions.md` or `.specify/skills/`, verify whether it is a symlink before treating it as a separate file.

## Resource Registry
Use this machine-maintained section to track reusable resource identifiers created by SpecKit commands. Keep entries deduplicated and sorted when updating this file. Record each resource as a single row in the corresponding horizontal Markdown table, and keep column names aligned with the corresponding agent/skill/tool templates. When no records exist, keep a single row with `None yet.` in the first column and `-` in the remaining columns.

### Agents
<!-- AGENTS_REGISTRY_START -->
<!-- Record each agent as one table row with the columns below. -->
| Agent Name | Agent ID | Description | Argument Hint | Target | User Invocable | Disable Model Invocation | Tools | Agents | Model | Handoffs | Canonical Path |
|------------|----------|-------------|---------------|--------|----------------|--------------------------|-------|--------|-------|----------|----------------|
| None yet. | - | - | - | - | - | - | - | - | - | - | - |
<!-- AGENTS_REGISTRY_END -->

### Skills
<!-- SKILLS_REGISTRY_START -->
<!-- Record each skill as one table row with the columns below. -->
| Skill Name | Skill ID | Description | Argument Hint | User Invocable | Disable Model Invocation | Canonical Path |
|------------|----------|-------------|---------------|----------------|--------------------------|----------------|
| None yet. | - | - | - | - | - | - |
<!-- SKILLS_REGISTRY_END -->

### Tools
<!-- TOOLS_REGISTRY_START -->
<!-- Record each tool as one table row with the columns below. -->
| Tool Name | Tool ID | Tool Type | Source Identifier | Aliases | Status | Last Updated | Description | Resource ID | Canonical Path |
|-----------|---------|-----------|-------------------|---------|--------|--------------|-------------|-------------|----------------|
| None yet. | - | - | - | - | - | - | - | - | - |
<!-- TOOLS_REGISTRY_END -->

